
[schemes]

[schemes.everforest_dark_hard]
  [schemes.everforest_dark_hard.primary]
    background = "#272e33"
    foreground = "#d3c6aa"
  [schemes.everforest_dark_hard.normal]
    black = "#414b50"
    red = "#e67e80"
    green = "#a7c080"
    yellow = "#dbbc7f"
    blue = "#7fbbb3"
    magenta = "#d699b6"
    cyan = "#83c092"
    white = "#d3c6aa"
  [schemes.everforest_dark_hard.bright]
    black = "#475258"
    red = "#e67e80"
    green = "#a7c080"
    yellow = "#dbbc7f"
    blue = "#7fbbb3"
    magenta = "#d699b6"
    cyan = "#83c092"
    white = "#d3c6aa"

[schemes.everforest_dark_medium]
  [schemes.everforest_dark_medium.primary]
    background = "#2d353b"
    foreground = "#d3c6aa"
  [schemes.everforest_dark_medium.normal]
    black = "#475258"
    red = "#e67e80"
    green = "#a7c080"
    yellow = "#dbbc7f"
    blue = "#7fbbb3"
    magenta = "#d699b6"
    cyan = "#83c092"
    white = "#d3c6aa"
  [schemes.everforest_dark_medium.bright]
    black = "#475258"
    red = "#e67e80"
    green = "#a7c080"
    yellow = "#dbbc7f"
    blue = "#7fbbb3"
    magenta = "#d699b6"
    cyan = "#83c092"
    white = "#d3c6aa"

[schemes.everforest_dark_soft]
  [schemes.everforest_dark_soft.primary]
    background = "#333c43"
    foreground = "#d3c6aa"
  [schemes.everforest_dark_soft.normal]
    black = "#4d5960"
    red = "#e67e80"
    green = "#a7c080"
    yellow = "#dbbc7f"
    blue = "#7fbbb3"
    magenta = "#d699b6"
    cyan = "#83c092"
    white = "#d3c6aa"
  [schemes.everforest_dark_soft.bright]
    black = "#4d5960"
    red = "#e67e80"
    green = "#a7c080"
    yellow = "#dbbc7f"
    blue = "#7fbbb3"
    magenta = "#d699b6"
    cyan = "#83c092"
    white = "#d3c6aa"

[schemes.everforest_light_hard]
  [schemes.everforest_light_hard.primary]
    background = "#fffbef"
    foreground = "#5c6a72"
  [schemes.everforest_light_hard.normal]
    black = "#5c6a72"
    red = "#f85552"
    green = "#8da101"
    yellow = "#dfa000"
    blue = "#3a94c5"
    magenta = "#df69ba"
    cyan = "#35a77c"
    white = "#e8e5d5"
  [schemes.everforest_light_hard.bright]
    black = "#5c6a72"
    red = "#f85552"
    green = "#8da101"
    yellow = "#dfa000"
    blue = "#3a94c5"
    magenta = "#df69ba"
    cyan = "#35a77c"
    white = "#e8e5d5"

[schemes.everforest_light_medium]
  [schemes.everforest_light_medium.primary]
    background = "#fdf6e3"
    foreground = "#5c6a72"
  [schemes.everforest_light_medium.normal]
    black = "#5c6a72"
    red = "#f85552"
    green = "#8da101"
    yellow = "#dfa000"
    blue = "#3a94c5"
    magenta = "#df69ba"
    cyan = "#35a77c"
    white = "#e0dcc7"
  [schemes.everforest_light_medium.bright]
    black = "#5c6a72"
    red = "#f85552"
    green = "#8da101"
    yellow = "#dfa000"
    blue = "#3a94c5"
    magenta = "#df69ba"
    cyan = "#35a77c"
    white = "#e0dcc7"

[schemes.everforest_light_soft]
  [schemes.everforest_light_soft.primary]
    background = "#f3ead3"
    foreground = "#5c6a72"
  [schemes.everforest_light_soft.normal]
    black = "#5c6a72"
    red = "#f85552"
    green = "#8da101"
    yellow = "#dfa000"
    blue = "#3a94c5"
    magenta = "#df69ba"
    cyan = "#35a77c"
    white = "#d8d3ba"
  [schemes.everforest_light_soft.bright]
    black = "#5c6a72"
    red = "#f85552"
    green = "#8da101"
    yellow = "#dfa000"
    blue = "#3a94c5"
    magenta = "#df69ba"
    cyan = "#35a77c"
    white = "#d8d3ba"

[colors]
  scheme = "everforest_dark_medium"
